### ISSUE TITLE
В меню можно было не писать везде капсом

### ISSUE THREAD

**Issue by DimaDK24** [Sergej-Karyuhin/my_hexal#2]
https://github.com/Sergej-Karyuhin/my_hexal/blob/42c090d9ebe7db4023b07add03b374d5c3454d2b/index.html#L22
Здесь и ниже капса в html можно было избежать с помощью css свойства [text-transform](https://devdocs.io/css/text-transform)
```css
.menu a.item {
  text-transform: uppercase;
}
```
HTML тогда выглядит проще и лучше
