### ISSUE TITLE
Не надо на все ссылки вешать padding и color

### ISSUE THREAD

**Issue by DimaDK24** [Sergej-Karyuhin/my_hexal#5]
https://github.com/Sergej-Karyuhin/my_hexal/blob/42c090d9ebe7db4023b07add03b374d5c3454d2b/style.css#L29

У тебя у всех ссылок будет такой padding. Это неправильно. Создашь ты еще в каком-нибудь месте ссылку и у нее тоже будет такой padding. А допустим там тебе вообще не нужен будет padding. И тебе придется это переписывать.

А вот `text-decoration: none` можно вешать на все ссылки. А цвет в данном случае лучше тоже только на эти ссылки вешать. Итого, этот селектор можно было разделить на 2:
```css
a {
  text-decoration: none;
}

.menu a {
  color: #ebebeb;
  margin: 0 15px;
}
```
