### ISSUE TITLE
Лишний css код / его неправильная организация

### ISSUE THREAD

**Issue by DimaDK24** [Sergej-Karyuhin/my_hexal#7]
https://github.com/Sergej-Karyuhin/my_hexal/blob/42c090d9ebe7db4023b07add03b374d5c3454d2b/style.css#L44

Рассмотрим этот твой код:
```css
a:hover, .item {
  color: rgba(46, 179, 152, 255);
}
.menu ul:first-child {
  color: rgba(46, 179, 152, 255);
}
```

Селектор `a:hover, .item` лучше написать в 2 строки для читабельности, поскольку это 2 совершенно разных селектора.
Получается селектором `.item` ты вешаешь на первую (активную) ссылку зеленый цвет. Селектор `.item` тут совершенно неясен, лучше будет `.menu-link-active`, как я написал [здесь](https://github.com/Sergej-Karyuhin/my_hexal/issues/6)

Потом следующим селектором `.menu ul:first-child` ты наверное хотел сделать тоже самое. То есть это лишний код, который должен делать то же самое и его нужно удалить.

Однако, этот селектор (`.menu ul:first-child`) не сработает в принципе. Он выберет не первый `li`, который находится внутри `.menu`, а первый `ul`, который находится внутри `.menu`. Почитай про first-child [здесь](https://devdocs.io/css/:first-child)

И лучше локально вешать на ссылки цвет при наведении (только в этом месте, а не на все ссылки). 

Итого для этого участка лучше будет вот такой html и css:
```html
<ul class="menu">
  <li class="menu-item-active"><a href="#">portfolio</a></li>
   ...
</ul>
```
```css
.menu > li > a:hover,
.menu-item-active > a {
  color: rgba(46, 179, 152, 255);
}
```
